# Generated by Django 3.2.16 on 2022-12-11 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_added', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('dog_breed', models.CharField(max_length=150)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('approx_age', models.CharField(max_length=50)),
                ('neutered', models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Unknown')], default=2)),
                ('microchipped', models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Unknown')], default=2)),
                ('circumstance', models.IntegerField(choices=[(0, 'Stray'), (1, 'Surrender'), (2, 'Seized'), (3, 'Other')], default=1)),
                ('pound_entry_date', models.DateField()),
                ('hold_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Hold'), (1, 'Available'), (2, 'Booked'), (3, 'Transferred to Rescue'), (4, 'Rehomed'), (5, 'Reclaimed'), (6, 'PTS'), (7, 'Death Natural Causes')], default=0)),
                ('urgency', models.IntegerField(choices=[(0, 'Red'), (1, 'Amber'), (2, 'Green')], default=2)),
                ('pound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-urgency', 'profile_added'],
            },
        ),
    ]
