# Generated by Django 3.2.16 on 2022-12-14 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.IntegerField(choices=[(0, 'Antrim'), (1, 'Armagh'), (2, 'Carlow'), (3, 'Cavan'), (4, 'Clare'), (5, 'Cork'), (6, 'Derry'), (7, 'Donegal'), (8, 'Down'), (9, 'Dublin'), (10, 'Fermanagh'), (11, 'Galway'), (12, 'Kerry'), (13, 'Kildare'), (14, 'Kilkenny'), (15, 'Laois'), (16, 'Leitrim'), (17, 'Limerick'), (18, 'Longford'), (19, 'Louth'), (20, 'Mayo'), (21, 'Meath'), (22, 'Monaghan'), (23, 'Offaly'), (24, 'Roscommon'), (25, 'Sligo'), (26, 'Tipperary'), (27, 'Tyrone'), (28, 'Waterford'), (29, 'Westmeath'), (30, 'Wexford'), (31, 'Wicklow')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pound_official_name',
            field=models.CharField(default='To be populated', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='rescue_official_name',
            field=models.CharField(default='To be populated', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pound_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
