# Generated by Django 3.2.16 on 2022-12-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_auto_20221214_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hold'), (1, 'Available'), (2, 'Booked'), (3, 'Transferred to Rescue'), (4, 'Rehomed'), (5, 'Reclaimed'), (6, 'PTS'), (7, 'Death Natural Causes'), (8, 'Booking Proposed')], default=0),
        ),
    ]
